# Generated by Django 5.2.7 on 2025-11-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='updated_at',
            new_name='last_edited',
        ),
        migrations.RemoveField(
            model_name='note',
            name='deleted_at',
        ),
    ]
