# Generated by Django 5.2.7 on 2025-12-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_updated_at_note_last_edited_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_user_note_title'),
        ),
    ]
