# Generated by Django 5.2.7 on 2025-12-05 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_note_unique_user_note_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='note',
            name='unique_user_note_title',
        ),
    ]
